# This is a workflow to open an issue in SourceLibraries when a push is made

name: Notify SourceLibraries Workflow

# Controls when the action will run. Will run on push to the master branch
on: 
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab or when the dispatch event is sent
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The following is the "notify" job
  notify:
    # The type of runner that the job will run on, can specify windows, other versions of Ubuntu etc.
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Load JS into variable
        id: load_js
        shell: bash
        run: |
          # Read IssueScript.js and escape special chars for GitHub output
          JS_CODE=$(< ./IssueScript.js)
          echo "code<<EOF" >> $GITHUB_OUTPUT
          echo "$JS_CODE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Execute external JS script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MAIN_REPO_TOKEN }}
          script: ${{ steps.load_js.outputs.code }}