# This is a workflow to open an issue in SourceLibraries when a push is made

name: Notify SourceLibraries Workflow

# Controls when the action will run. Will run on push to the master branch
on: 
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab or when the dispatch event is sent
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The following is the "notify" job
  notify:
    # The type of runner that the job will run on, can specify windows, other versions of Ubuntu etc.
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./scripts
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create issue in main repo
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PARENT_REPO_TOKEN }} # PAT with "repo" on the main repo
          run: |
            ./scripts/IssueScript.js
            
